#!/bin/sh
python createdb.py
python getmediathread/manage.py syncdb --noinput
python getmediathread/manage.py migrate --noinput
python mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static
python getmediathread/manage.py collectstatic --noinput -v0